Init project
irfanalmsyah/capstone pull request #1
Opened 2024-03-03 16:26 UTC by mirzahm14

inisialisasi projek awal sama konek db

2024-03-03 17:21 UTC, irfanalmsyah requested changes
1. semua file/folder yang ada di folder webapi pindahkan ke root directory
instead of struktur nya seperti ini:
```
├── README.md
└── webapi/
    ├── bin/
    ├── Controllers/
    ├── Data/
    └── Obj/
        └── Debug/
            project.assets.json
            project.nuget.cache
            webapi.csproj.nuget.dgspec.json
    ├── Properties/
    ├── appsettings.json
    ├── Program.cs
    .
    .
    .
```
jadi seperti ini:
```
├── README.md
├── bin/
├── Controllers/
├── Data/
├── Obj/
    └── Debug/
        project.assets.json
        project.nuget.cache
        webapi.csproj.nuget.dgspec.json
├── Properties/
├── appsettings.json
├── Program.cs
.
.
.
```
2. Tambahkan file `.gitignore` di root directory
[Git Ignore](https://git-scm.com/docs/gitignore) itu adalah file yang berisi daftar file/folder yang tidak ingin di track oleh git. Misal kalau di project ASP.NET Core, ada folder `bin` dan `obj` yang isinya file hasil build, kita tidak ingin file-file tersebut di track oleh git (karena tidak penting dan bisa di generate ulang). Maka kita bisa menambahkan `bin` dan `obj` ke dalam file `.gitignore` tersebut. Untuk project ASP.NET Core, bisa menggunakan file `.gitignore` yang sudah disediakan oleh Visual Studio. Bisa di copy dari [sini](https://github.com/dotnet/core/blob/main/.gitignore)

3. Jelaskan detail step by step cara menjalankan servernya di file `README.md` yang orang awam (tidak pernah menggunakan ASP.NET Core) juga bisa mengerti. Misal `1. Create DefaultConnection variable` itu create nya di file apa? dll.

2024-03-03 17:21 UTC, irfanalmsyah commented on README.md
tambahin detailed instruction step-by-step gimana cara jalanin servernya

2024-03-03 18:14 UTC, ilhmhakim commented
Same as what've Ipan just said. Add credential, configuration, and unimportant package into .gitignore file. It'll make the development become clean, better, and more secure because the configuration can't be seen and public can't track it. But, you can untrack it first just like on this [link](https://ioflood.com/blog/solved-git-ignore-not-working-git-troubleshooting-guide/#:~:text=A%20common%20issue%20many%20users,rm%20%2D%2Dcached%20.) because you didn't add it before.

2024-03-04 06:30 UTC, closed without merging

2024-03-04 06:30 UTC, mirzahm14 commented
canceled