add course models and controllers
irfanalmsyah/capstone pull request #4
Opened 2024-03-08 10:07 UTC by andyanamafaza

Add Course, CourseType, CourseClass Models
Add Course controller
Finish course create and get detail

2024-03-09 06:12 UTC, irfanalmsyah requested changes
1. Tambahkan migration files
2. ganti `webapi` jadi `WebApi`
3. pastikan attribute yang unique diterapkan. [Referensi](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.indexbuilder.isunique?view=efcore-8.0#microsoft-entityframeworkcore-metadata-builders-indexbuilder-isunique(system-boolean))

2024-03-15 06:17 UTC, ilhmhakim commented
Banyak penamaan variabel/atribut yang kurang konsisten. Usahakan penamaan variabel/atribut dibuat menjadi camelCase. Untuk penamaan class sudah aman menggunakan PascalCase.

2024-03-15 06:19 UTC, ilhmhakim requested changes

2024-03-15 06:19 UTC, ilhmhakim commented on WebApi/Migrations/20240315044745_CoursesInitMigration.cs
> +                    Id = table.Column<int>(type: "int", nullable: false)
Ubah format penamaan variabel atau atribut menjadi camelCase

2024-03-18 08:17 UTC, irfanalmsyah requested changes

2024-03-18 08:17 UTC, irfanalmsyah commented on WebApi/Controllers/CourseController.cs
> +                        CourseTypeT = (CourseType.CourseTypeEnum)ct.Type,
req.body
```json
{
    "semester_id": 1,
    "name": "Algoritma dan Dasar Pemrograman",
    "code": "kom120b",
    "semesters": 1,
    "course_type": [
        {
            "type": 1,
            "credit": 2
        },
        {
            "type": 2,
            "credit": 1
        }
    ]
}
```
res.body
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-a6b141a03334504fa153569d7eddef29-1f6e564419a317c7-00",
    "errors": {
        "CourseType": [
            "The CourseType field is required."
        ]
    }
}
```

2024-04-04 12:03 UTC, andyanamafaza commented on WebApi/Migrations/20240315044745_CoursesInitMigration.cs
> +                    Id = table.Column<int>(type: "int", nullable: false)
Jika mengikuti format penamaan dari [dotnet ](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-rules)maka sudah benar dengan menggunakan PascalCase

2024-04-05 13:35 UTC, irfanalmsyah requested changes
1. jika create course nya gagal karena `"Course with the same code already exists"`, id nya tetap increment sedangkan datanya tidak ditambahkan ke database.

misal dibuat suatu course, sukses dengan id 1
dibuat course baru dengan code yang sama dengan id 1, gagal.
dibuat course baru lainnya dengan code yang berbeda, sukses namun id nya 3 (seharusnya 2)

2. atribut "semesters" tidak divalidasi e.g. jika kosong tidak error.
3. atribut "semesters" tidak muncul di response body

2024-04-06 09:40 UTC, merged